from pathlib import Path

ORG = "akalino"
REPO = "CSCI_2020"
BRANCH = "HEAD"

BASE = f"https://mybinder.org/v2/gh/{ORG}/{REPO}/{BRANCH}?urlpath=lab/tree/"


def nice_title(stem: str) -> str:
    # Turn filenames into readable labels
    return stem.replace("_", " ").replace("-", " ").strip()


def main() -> None:
    root = Path("modules")
    if not root.exists():
        raise SystemExit("Could not find ./modules. Run this from the repo root.")

    lines = []
    lines.append("# Binder links (auto-generated)\n")
    lines.append("> Generated by `tools/make_binder_links.py`\n\n")

    for module_dir in sorted(root.glob("module*/")):
        ipynbs = sorted(module_dir.rglob("*.ipynb"))
        if not ipynbs:
            continue

        lines.append(f"## {module_dir.name}\n")
        for nb in ipynbs:
            rel = nb.as_posix()
            url = BASE + rel
            lines.append(f"- {nice_title(nb.stem)}: {url}\n")
        lines.append("\n")

    out = Path("BINDER_LINKS.md")
    out.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {out.resolve()}")


if __name__ == "__main__":
    main()
